image:
  repository: localhost:5000/gitea/gitea
  tag: 1.15.3
  pullPolicy: IfNotPresent
service:
  ssh:
    type: NodePort
    port: 22
ingress:
  enabled: false
  # className: nginx
  annotations: { }
  # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  hosts:
    - host: git.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: [ ]
  #  - secretName: chart-example-tls
  #    hosts:
  #      - git.example.com
persistence:
  enabled: true
  size: 8Gi
  storageClass: standard
gitea:
  admin:
    existingSecret: gitea-admin-secret
    email: "ben.wangz@foxmail.com"
  config:
    default:
      APP_NAME: Gitea
      RUN_USER: git
      RUN_MODE: prod
    repository:
      MAX_CREATION_LIMIT: 10
      DISABLED_REPO_UNITS: repo.wiki,repo.ext_wiki
      DEFAULT_REPO_UNITS: repo.code,repo.releases,repo.issues,repo.pulls,repo.wiki,repo.projects
      DISABLE_STARS: true
    ui:
      SEARCH_REPO_DESCRIPTION: false
    server:
      LANDING_PAGE: login
      DOMATN: gitea.conti.net
      SSH_DOMAIN: gitea.conti.net
    admin:
      DISABLE_REGULAR_ORG_CREATION: true
    security:
      INSTALL_LOCK: true
    service:
      DISABLE_REGISTRATION: true
      ENABLE_NOTIFY_MAIL: true
      DEFAULT_ALLOW_CREATE_ORGANIZATION: false
      SHOW_REGISTRATION_BUTTON: false
      explore:
        DISABLE_USERS_PAGE: true
    mailer:
      ENABLED: true
      IS_TLS_ENABLED: true
      MAILER_TYPE: smtp
      HOST: smtpdm.aliyun.com:465
      FROM: messenger@email.catconti.icu
      USER: messenger@email.catconti.icu
      PASSWD: WSXqaz1234
    other:
      SHOW_FOOTER_VERSION: false
  database:
    builtIn:
      postgresql:
        enabled: true
      mysql:
        enabled: false
      mariadb:
        enabled: false
  cache:
    builtIn:
      enabled: true
memcached:
  image:
    registry: localhost:5000/docker.io
    repository: bitnami/memcached
    tag: 1.6.9-debian-10-r114
    pullPolicy: IfNotPresent
  service:
    port: 11211
  persistence:
    enabled: false
  metrics:
    image:
      registry: localhost:5000/docker.io
      repository: bitnami/memcached-exporter
      tag: 0.8.0-debian-10-r105
      pullPolicy: IfNotPresent
postgresql:
  global:
    postgresql:
      postgresqlDatabase: gitea
      postgresqlUsername: gitea
      postgresqlPassword: gitea
      servicePort: 5432
  image:
    registry: localhost:5000/docker.io
    repository: bitnami/postgresql
    tag: 11.11.0-debian-10-r62
    pullPolicy: IfNotPresent
  persistence:
    size: 10Gi
    storageClass: standard
  volumePermissions:
    image:
      registry: localhost:5000/docker.io
      repository: bitnami/bitnami-shell
      tag: "10"
      pullPolicy: IfNotPresent
  metrics:
    image:
      registry: localhost:5000/docker.io
      repository: bitnami/postgres-exporter
      tag: 0.9.0-debian-10-r34
      pullPolicy: IfNotPresent