image:
  repository: localhost:5000/docker.io/sonatype/nexus3
  tag: 3.37.3
  pullPolicy: IfNotPresent
nexus:
  env:
    - name: INSTALL4J_ADD_VM_PARAMS
      value: "-Xms1200M -Xmx1200M -XX:MaxDirectMemorySize=2G -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
    - name: NEXUS_SECURITY_RANDOMPASSWORD
      value: "true"
  properties:
    override: false
    data:
      nexus.scripts.allowCreation: true
  nexusPort: 8081
deployment:
  initContainers:
  #   - name: fmp-volume-permission
  #   image: busybox
  #   imagePullPolicy: IfNotPresent
  #   command: ['chown','-R', '200', '/nexus-data']
  #   volumeMounts:
  #     - name: nexus-data
  #       mountPath: /nexus-data
  # Uncomment and modify this to run a command after starting the nexus container.
  postStart:
    command:    # '["/bin/sh", "-c", "ls"]'
  preStart:
    command:    # '["/bin/rm", "-f", "/path/to/lockfile"]'
  terminationGracePeriodSeconds: 120
  additionalContainers:
  additionalVolumes:
  additionalVolumeMounts:
ingress:
  enabled: true
  ingressClassName: nginx
  annotations: {}
  hostPath: /
  hostRepo: nexus-test.cnconti.cc
  tls:
    - secretName: nexus-test.cnconti.cc-tls
      hosts:
        - nexus-test.cnconti.cc
service:
  name: nexus3
  enabled: true
  labels: {}
  annotations: {}
  type: ClusterIP
route:
  enabled: false
  name: docker
  portName: docker
  labels:
  annotations:
  # path: /docker
nexusProxyRoute:
  enabled: false
  labels:
  annotations:
  # path: /nexus
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  storageClass: "standard"
  storageSize: 8Gi
config:
  enabled: false
  mountPath: /sonatype-nexus-conf
  data: []
secret:
  enabled: false
  mountPath: /etc/secret-volume
  readOnly: true
  data: []
serviceAccount:
  create: true
  annotations: {}
  name: ""
