image:
  repository: localhost:5000/docker.io/verdaccio/verdaccio
  tag: 5.2.0
  pullPolicy: IfNotPresent
  pullSecrets: []
ingress:
  enabled: true
  className: nginx
  paths:
    - /
  hosts:
    - npm.cnconti.cc
  annotations:
    cert-manager.io/cluster-issuer: self-signed-clusterissuer
  tls:
    - secretName: npm.test.cnconti.cc-tls
      hosts:
        - npm.test.cnconti.cc
configMap: |
  storage: /verdaccio/storage/data
  web:
    enable: true
    title: Verdaccio
    gravatar: true
  auth:
    htpasswd:
      file: /verdaccio/storage/htpasswd
  uplinks:
    npmjs:
      url: https://registry.npm.taobao.org/
      agent_options:
        keepAlive: true
        maxSockets: 40
        maxFreeSockets: 10
  packages:
    '@*/*':
      # scoped packages
      access: $all
      publish: $authenticated
      proxy: npmjs

    '**':
      access: $all
      publish: $authenticated
      proxy: npmjs
persistence:
  enabled: true
  storageClass: standard
  accessMode: ReadWriteOnce
  size: 8Gi