image:
  registry: docker-registry-ops-dev.lab.zjvis.net:32443
  repository: docker.io/bitnami/nginx
  tag: 1.21.3-debian-10-r29
  pullPolicy: IfNotPresent
replicaCount: 1
service:
  type: LoadBalancer
  annotations:
    purelb.io/service-group: purelb-layer2-ippool