common:
  setPVOwnerRef: true
classes:
  - name: rook-data
    hostDir: /local-static-provisioner/rook-ceph/data
    volumeMode: Block
    fsType: ext4
    namePattern: "*"
    blockCleanerCommand:
    storageClass: true
daemonset:
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master