common:
  setPVOwnerRef: true
classes:
  - name: rook-monitor
    hostDir: /local-static-provisioner/rook-ceph/monitor
    volumeMode: Filesystem
    fsType: xfs
    namePattern: "*"
    blockCleanerCommand:
    storageClass: true
daemonset:
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master