image:
  repository: registry
  tag: 2.7.1
ingress:
  enabled: false
persistence:
  enabled: true
  size: 100Gi
  storageClass: common-multi
configData:
  auth:
    htpasswd:
      realm: basic-realm
      path: /opt/auth/htpasswd
secrets:
  htpasswd: "admin:$2y$05$5K2nizsCKRv/lTYCJ08RAOM5sFCI.czI2RxQZu2IbWmz9PoS0J2GW"



