apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: self-signed-clusterissuer
spec:
  acme:
    email: ben.wangz@foxmail.com
    privateKeySecretRef:
      name: self-signed-clusterissuer
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          webhook:
            config:
              accessTokenSecretRef:
                key: access-token
                name: alidns-webhook-secrets
              regionId: cn-beijing
              secretKeySecretRef:
                key: secret-key
                name: alidns-webhook-secrets
            groupName: ops.zjvis.net
            solverName: alidns-solver