image:
  repository: docker-registry-ops.lab.zjvis.net:32443/docker.io/aiworks-frontend-vue
  tag: "22d342ad4-1.0.0-C4f979aa"
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: alidns-webhook-letsencrypt
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/proxy-body-size: 2g
    nginx.org/client-max-body-size: 2g
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
  hosts:
    - host: nebula-stable.lab.zjvis.net
      paths:
        - path: /(.*)
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - nebula-stable.lab.zjvis.net
      secretName: nebula-stable.lab.zjvis.net-tls
extraNginxConfiguration: |-
  location /configuration/entrypoint {
    add_header Content-Type text/plain;
    return 200 '{
        "VUE_APP_KG_CONSTRUCTION": "/service/kgconstruct/",
        "VUE_APP_KG_APPLICATION": "/service/knowledge/"
    }';
  }
