apiVersion: v1
kind: ServiceAccount
metadata:
  name: conti-test  # sa-name
  namespace: test   # sa-namespace
  labels:
    app.kubernetes.io/service: my-sshd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: conti-test-role
  namespace: test
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list", "patch","update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: conti-test-rolebinding
  namespace: test
subjects:
  - kind: ServiceAccount
    name: conti-test
    namespace: test
roleRef:
  kind: Role
  name: conti-test-role
  apiGroup: "rbac.authorization.k8s.io"