apiVersion: v1
kind: ServiceAccount
metadata:
  name: conti-test  # sa-name
  namespace: test   # sa-namespace
  labels:
    app.kubernetes.io/service: my-sshd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: conti-test-clusterrole
rules:
  - apiGroups: [""]
    resources: ["pods" "services"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: conti-test-rolebinding
  namespace: middleware
subjects:
  - kind: ServiceAccount
    name: conti-test
    namespace: test
roleRef:
  kind: ClusterRole
  name: conti-test-clusterrole
  apiGroup: "rbac.authorization.k8s.io"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: conti-test-rolebinding
  namespace: application
subjects:
  - kind: ServiceAccount
    name: conti-test
    namespace: test
roleRef:
  kind: ClusterRole
  name: conti-test-clusterrole
  apiGroup: "rbac.authorization.k8s.io"
