apiVersion: v1
kind: ServiceAccount
metadata:
  name: conti-sa
  labels:
    app.kubernetes.io/service: my-sshd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: conti-rolebinding.v1
  namespace: application
  labels:
    app.kubernetes.io/service: my-sshd
  annotations: {}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: conti-sa
