apiVersion: v1
kind: ServiceAccount
metadata:
  name: conti-sa
  labels:
    app.kubernetes.io/service: my-sshd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: conti-role
  labels:
    app.kubernetes.io/service: my-sshd
  annotations: {}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - proxy
  - apiGroups:
      - ""
    resources:
      - services/proxy
    verbs:
      - get
  - apiGroups:
      - ""
    resourceNames:
      - kubernetes-dashboard-key-holder
      - kubernetes-dashboard-certs
      - kubernetes-dashboard-csrf
    resources:
      - secrets
    verbs:
      - get
      - update
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: conti-rolebinding.v1
  namespace: application
  labels:
    app.kubernetes.io/service: my-sshd
  annotations: {}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: conti-role.v1
subjects:
  - kind: ServiceAccount
    name: conti-sa.v1




apiVersion: v1
kind: ServiceAccount
metadata:
  name: conti-sa
  labels:
    app.kubernetes.io/service: my-sshd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: conti-rolebinding.v1
  namespace: application
  labels:
    app.kubernetes.io/service: my-sshd
  annotations: {}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: conti-sa
